stages:
  get-features:
    cmd: python3 scripts/data-processing/get_features.py
    deps:
    - scripts/data-processing/get_features.py
    outs:
    - data/stage1
  fill-na:
    cmd: python3 scripts/data-processing/fill_na.py
    deps:
    - scripts/data-processing/fill_na.py
    outs:
    - data/stage2
  text-to-numeric:
    cmd: python3 scripts/data-processing/text_to_numeric.py
    deps:
    - scripts/data-processing/text_to_numeric.py
    outs:
    - data/stage3

