stages:
  get-features:
    cmd: python3 scripts/data-processing/get_features.py
    deps:
    - scripts/data-processing/get_features.py
    outs:
    - data/stage1
  fill-na:
    cmd: python3 scripts/data-processing/fill_na.py
    deps:
    - scripts/data-processing/fill_na.py
    outs:
    - data/stage2
  text-to-numeric:
    cmd: python3 scripts/data-processing/text_to_numeric.py
    deps:
    - scripts/data-processing/text_to_numeric.py
    outs:
    - data/stage3
  split:
    cmd: python3 scripts/data-processing/train_test_split.py
    deps:
    - scripts/data-processing/train_test_split.py
    params:
    - split.split_ratio
    outs:
    - data/stage4
  train:
    cmd: python3 scripts/model-learning/dt.py
    deps:
    - scripts/model-learning/dt.py
    params:
    - train.max_depth
    - train.seed
    outs:
    - models/dt.pkl
  evaluate:
    cmd: python3 scripts/model-learning/evaluate.py
    deps:
    - models/dt.pkl
    - scripts/model-learning/evaluate.py
    metrics:
    - evaluate/score.json:
        cache: false
